image: ruby:2.6

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r web/* .public/
    - mv .public public
    - gem install jekyll bundler
    - jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master